language: python

python:
  - "2.7"
  - "3.2"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

before_install:
    - pip install pytest pytest-cov

script:
  - python litss.py conditionals.py hellopython.py tuples.py
